networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
services:
  auth-service:
    build:
      context: ..
      dockerfile: build/auth-service.dockerfile
    restart: always
    env_file:
      - ../configs/example.env
    ports:
      - "8080:82"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medods
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
